### ISSUE TITLE
evtest: No such file or directory

### ISSUE THREAD

**Issue by ManuelDo** [mqudsi/syngesture#11]
When I start syngestures I only get the evtest: No such file or directory message

**Comment by mqudsi** [comment]
Did you configure syngestures.toml with the path to your input device?

**Comment by ManuelDo** [comment]
Im using this path /dev/input/event0
If I open it only with evtest I can test it

**Comment by ManuelDo** [comment]
This is my config

```
# Syngestures configuration file, version 1

# This file should be placed in any of the following paths.
# * $PREFIX/syngestures.toml (for global configuration)
# * $PREFIX/syngestures.d/*.toml (for global configuration, separate file per device)
# * $XDG_CONFIG_HOME/syngestures.toml (for per-user configuration)
# * $XDG_CONFIG_HOME/syngestures.d/*.toml (for per-user configuration, separate file per device)
#
# If $XDG_CONFIG_HOME is not set, $HOME/.config/ is used in its place.

[[device]]
device = "/dev/input/event0"
gestures = [
	# Emulate right-click. Don't use this if two-finger tap to right-click already works
	# { type = "tap", fingers = 2, execute = "xdotool click 3" },

	# Emulate middle-click
	# { type = "tap", fingers = 3, execute = "xdotool click 2" },

	# Navigate next
	{ type = "swipe", direction = "right", fingers = 3, execute = "xdotool key alt+Right" },
	# Navigate previous
	{ type = "swipe", direction = "left", fingers = 3, execute = "xdotool key alt+Left" },
	# Next desktop/workspace
	{ type = "swipe", direction = "right", fingers = 4, execute = "xdotool key Super_L+Right" },
	# Previous desktop/workspace
	{ type = "swipe", direction = "left", fingers = 4, execute = "xdotool key Super_L+Left" },

	# Enter multi-tasking view
	{ type = "swipe", direction = "up", fingers = 4, execute = "xdotool key Super_L+Down" },
	# Leave multi-tasking view
	{ type = "swipe", direction = "down", fingers = 4, execute = "xdotool key Super_L+Down" },
]
```

**Comment by mqudsi** [comment]
Ok, and is `/dev/input/event0` is the correct path to your trackpad input device?

**Comment by mqudsi** [comment]
Did you build syngestures from source or use a precompiled package?

**Comment by mqudsi** [comment]
Oh, is `evtest` in your `$PATH`? 

execute the following:

```sh
> which evtest
> echo $PATH
```

**Comment by ManuelDo** [comment]
> Did you build syngestures from source or use a precompiled package?

Precompiled package

**Comment by ManuelDo** [comment]
> Oh, is `evtest` in your `$PATH`?
> 
> execute the following:
> 
> ```shell
> > which evtest
> > echo $PATH
> ```

I executed that command, still not working

**Comment by mqudsi** [comment]
I meant for you to share the output of those commands.

**Comment by ManuelDo** [comment]
which evtest
/usr/bin/evtest


echo $PATH
/usr/bin/evtest:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games

**Comment by stibinator** [comment]
Having the same issue. evtest is in /usr/bin and it's on the $PATH. I can run evtest from the command line, but I still get file or folder not found. Using the binary.

**Comment by mqudsi** [comment]
I think these errors are not from `syngestures` saying that `evtest` couldn't be found, but rather from `evtest` saying the mouse/touchpad couldn't be found.

I've dropped `evtest` completely from the code as it was causing poor battery life and have a beta of the new release you guys can try. Here's the latest version from git compiled and bundled as a .tar.gz:

[syngestures.beta.tar.gz](https://github.com/mqudsi/syngesture/files/11518572/syngestures.tar.gz)

**Comment by mqudsi** [comment]
I'm closing this issue as the current version of syngestures does not use `evtest` and this error (whether it is coming from syngestures or from evtest) isn't applicable there. I haven't received any feedback on the beta build I provided, but I'll assume that means it has been working fine for @stibinator and @ManuelDo. Feel free to reply here or open a new issue with any other feedback!

**Comment by stibinator** [comment]
That is working perfectly, thank you so much!

**Comment by stibinator** [comment]
If I want to run it as a service without logging, how do I do that?
