### ISSUE TITLE
Lowering/changing sensitivity

### ISSUE THREAD

**Issue by askvictor** [mqudsi/syngesture#12]
I'm finding this is causing unwanted gestures in some cases - e.g. I have two-finger back/forward configured, but I also use two finger scrolling; it frequently triggers a back or forward action when I finish my scroll action. I'm not sure how much of this is syngesture's responsibility vs one of the lower level systems. Any pointers to where I can tweak this behaviour?

Great program by the way!

**Comment by mqudsi** [comment]
Hi thanks for opening the issue. I personally use three finger swipes and two finger scrolls but I can see how the issue you describe would manifest if you are using two finger for both. 

There is a constant value in the source code that is the “minimum distance” the gesture should cover before it will be recognized (i.e. if it’s less than that distance it is discarded). Are you able to build the project from source?

**Comment by askvictor** [comment]
Thanks for the quick reply! Yep, can build from source; I'll have a play with it

**Comment by mqudsi** [comment]
I’m pretty sure you just need to tweak this line:

https://github.com/mqudsi/syngesture/blob/c68b68bf7bec6cd25c1fb34f90a55b25e2ab10e5/src/events.rs#L8-L9

edit: also I think the comment is wrong. It’s certainly not 100mm of minimum travel.

**Comment by askvictor** [comment]
I've bumped it up to 1000 and seems a lot better so far; I'll run with that for a little while and see how it goes. Would be nice to have that in the config file.

**Comment by mqudsi** [comment]
It’s not really something you’d normally want to play around with — it’s just that I didn’t yet arrive at a great value. The existing value was just something I picked roughly and it seemed to work well enough that I never bothered with changing it (but again I prefer to have horizontal scroll for two fingers so I didn’t run into the case you describe). It *should* be driver/hardware agnostic so if we find a better value it should be OK to just update it.

**Comment by mqudsi** [comment]
@askvictor Just checking in to see how it goes for you with syngestures. Was a `MAX_DISTANCE` of `1_000f64` the right value for you?

**Comment by mqudsi** [comment]
This variable was renamed to `MIN_SWIPE_DISTANCE` to be easier to find/understand and its value was bumped up to 300. 1000 was too high in my own testing (caveat: on my own hardware).
