### ISSUE TITLE
/usr/local config

### ISSUE THREAD

**Issue by begin-theadventure** [mqudsi/syngesture#13]
Shouldn't `/usr/local` in [`config.rs`](https://github.com/mqudsi/syngesture/blob/1.0.1/src/config.rs#L42) be changed to `/etc`?
[Filesystem Hierarchy Standard](https://www.pathname.com/fhs/pub/fhs-2.3.html#USRLOCALLOCALHIERARCHY) - "Note that /usr/etc is still not allowed: programs in /usr should place configuration files in /etc"
[Arch Wiki](https://wiki.archlinux.org/title/Arch_package_guidelines#Package_etiquette) - "Packages should never be installed to /usr/local/".

**Comment by mqudsi** [comment]
Thanks for noticing an issue with where the configuration files are loaded from and opening this thread,  @begin-theadventure. I have a few different answers/points related to your questions:

* `PREFIX` is a de facto environment/make variable always set when compiling an application/library (as a package or w/out any package integration) and indicates what all standard locations should be prefixed with - so the link in your post to config.rs:42 (`get_prefix()`) is fine and wouldn't be touched regardless of anything. In this case, it's saying if the user hasn't overridden `PREFIX` then install the binary to /usr/local/bin/syngestures (and other stuff would be incidental).
* For me personally, my unix reference is first and foremost (Free)BSD and not Arch or any other Linux distribution. FreeBSD's [`hier(7)`](https://man.freebsd.org/cgi/man.cgi?hier) explains the hierarchy on FreeBSD, where packages are, in fact, installed to `/usr/local/` together with their (sometimes user-editable) configuration files.
* Even for Arch, I don't think anything in this package conflicts with installing the application to a prefix of `/usr/local` by default - this repo does **not** house a *package*, it houses an open source application that distro maintainers *may* choose to package on their own. I think there is consensus that a manually-downloaded, hand-compiled, and hand-installed app `foo` should be installed to `/usr/local/` so it doesn't interfere with binaries installed via the (system) package manager.

That's all just for the `PREFIX` stuff. Now I agree with you that the default *global* configuration directory should be `/etc/`  (even if prefix was `/usr/local`) and that it's a bug `/etc/syngestures.toml` and `/etc/sysngestures.d/*.toml` aren't searched by the current logic. Those _should_ indeed be queried first before overriding/merging with a configuration from `$PREFIX/etc/syngestures...`. (I'm pretty sure the first version did that and the current behavior is a regression, but I could be wrong and misremembering.)

**Comment by begin-theadventure** [comment]
Thanks for the reply and explanation.
