### ISSUE TITLE
SUID bit documentation

### ISSUE THREAD

**Issue by pckilgore** [mqudsi/syngesture#3]
I'm not a os guru but did you mean SUID bit on `evtest`, e.g., `chmod u+s` not the sticky bit `chmod +t`?

The latter works, the former does not (and sorta makes sense that it doesn't to me).

Also, minor thing since the executed commands appear arbitrary, but `xdotool` was an additional dependency requirement for me just testing the out of the box config.

Other than that, this worked really well! Thanks!

**Comment by mapperfr** [comment]
Hi @pckilgore, could you detail the command you ran to set the sticky bit on evtest? 
I  I thought one could only set it on a file or a directory, what would be the path to the evtest executable then?
Thanks a lot for your help!

**Comment by mqudsi** [comment]
@pckilgore thanks, you are entirely correct and that was a mistake I should have known far better than to make! 

Regarding the second point: note that `xdotool` is mentioned in the README in the configuration section; it's intentionally not an explicit dependency as one may - theoretically, at any rate - map a gesture to any arbitrary command of their choosing.

@mapperfr I have added a parenthetical to the readme that contains the instructions on setting the SUID bit. It should be as simple as executing `sudo chmod u+s $(which evtest)` in a posix-compatible shell.
