### ISSUE TITLE
How Hard Would It Be To Make Software That Works Like Mac TrackPad?

### ISSUE THREAD

**Issue by MANTENN** [mqudsi/syngesture#4]
Basically responsive to the gestures. How the scrolling works with two fingers and apply that to all gestures.

**Comment by mqudsi** [comment]
Sorry, I don’t understand the question. Can you clarify?

**Comment by MANTENN** [comment]
@mqudsi Yeah sure. If you have an iPhone the gesture bar would be the example(10 and up). It's the same on windows, did you use a MacBook or a laptop with good gestures?

**Comment by MANTENN** [comment]
The way this works is it detects motion in a certain way and sends a keyboard command. I'm looking for something that's a bit more responsive and fluid with the gestures like on the MacBook or Windows(Dell XPS). The scrolling would be a good example, I'm looking to take that and apply it to pinch and swipe gestures. 

https://www.youtube.com/watch?v=dzCjkHqf26o

**Comment by mqudsi** [comment]
Again, I don't know what "more responsive" and "fluid" is in reference to. I have used macOS on a MacBook and I have an iPhone, in addition to using Windows 10 with a trackpad.

Can you please be more technical?

**Comment by MANTENN** [comment]
> Again, I don't know what "more responsive" and "fluid" is in reference to. I have used macOS on a MacBook and I have an iPhone, in addition to using Windows 10 with a trackpad.
> 
> Can you please be more technical?

When pinching, instead of sending keyboard shortcuts, send a tap gesture event in the browser. I don't know how else to explain it. By responsive and fluid I mean feel interactive, so when you push an object in the real world it moves. It only moves as much as you push it. I would like to achieve the same--referring to the box pushing analogy--interaction with a trackpad. I don't know much about Ubuntu software development.

**Comment by MANTENN** [comment]
https://www.reddit.com/r/gnome/comments/9hsw0p/nice_touchpad_gestures_improvement_in_gnome_330/

Sorry about the hassle. Looks like it exists already.

**Comment by mqudsi** [comment]
> By responsive and fluid I mean feel interactive, so when you push an object in the real world it moves. It only moves as much as you push it. I would like to achieve the same--referring to the box pushing analogy--interaction with a trackpad. I don't know much about Ubuntu software development.

That's a much better description, thank you :)

**Comment by MANTENN** [comment]
> > By responsive and fluid I mean feel interactive, so when you push an object in the real world it moves. It only moves as much as you push it. I would like to achieve the same--referring to the box pushing analogy--interaction with a trackpad. I don't know much about Ubuntu software development.
> 
> That's a much better description, thank you :)

https://github.com/JoseExposito/touchegg

Here is what I ended up using in case anyone is interested in finding something thats good.
