### ISSUE TITLE
How to set the sticky bit on evtest

### ISSUE THREAD

**Issue by mapperfr** [mqudsi/syngesture#5]
Hi,
Not an issue, more of a call for support :)
I'm trying to make syngestures work on Ubuntu 20.10 but I'm stuck at the evtest sticky bit part: could you precise what command do I need to run to set it? I thought you could only set it on a file, what would be the path to the evtest executable then?
Thanks a lot for your help!

**Comment by mapperfr** [comment]
Closing as it is very related to #3

**Comment by mqudsi** [comment]
@mapperfr I've answered the question in #3 but `sudo chmod u+s $(which evtest)` should do the trick.
