### ISSUE TITLE
evtest: No such file or directory

### ISSUE THREAD

**Issue by slenderq** [mqudsi/syngesture#6]
Trying to use this on a GalliumOS (based on XUbuntu).

When I run:
`syngestures`
I get:
`evtest: No such file or directory`

Although, I have evtest installed with `apt`

`which evtest`
`/usr/bin/evtest`

Also noting that evtest runs on my system just fine.

evtest is also accessible from the root user, running `syngestures` as root does not help.

Any ideas? 
Thanks,
Justin

**Comment by slenderq** [comment]
Update: just tried `sudo chmod u+s $(which evtest)` based on older issues. No luck.

Also tried to reinstalling. No luck.

**Comment by mqudsi** [comment]
syngestures does its own checking for `evtest`, if it's not found it prints 

> Cannot find `evtest` - make sure it is installed and try again!

Which means this isn't about `evtest` not being found.

You might be seeing an error *from* `evtest` - in that case, the problem is with the path to the input device in your `syngestures.toml` configuration file.

**Comment by slenderq** [comment]
Ah that is totally it. Thanks for the quick response. Putting the same path I used into `evtest` recreated the error.

**Comment by shantanu-shantanu** [comment]
Hi I am having problem knowing the device. Can you kindly take a look and tell me what should I put in device. bcm 5974 is the trackpad's name as per xinput list. And thank you  in advance.

`$ dmesg
[    3.910432] usb 2-1.8.3: New USB device found, idVendor=05ac, idProduct=0252, bcdDevice= 2.19
[    3.910437] usb 2-1.8.3: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    3.910440] usb 2-1.8.3: Product: Apple Internal Keyboard / Trackpad
[    3.910441] usb 2-1.8.3: Manufacturer: Apple Inc.
[    3.920923] input: Apple Inc. Apple Internal Keyboard / Trackpad as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.8/2-1.8.3/2-1.8.3:1.0/0003:05AC:0252.0002/input/input6
[    3.923149] raid6: sse2x1   gen()  8326 MB/s
[    3.923154] raid6: using algorithm sse2x2 gen() 10565 MB/s
[    3.940145] raid6: .... xor() 5950 MB/s, rmw enabled
[    3.940148] raid6: using ssse3x2 recovery algorithm
[    3.940560] xor: automatically using best checksumming function   avx       
[    3.940843] async_tx: api initialized (async)
[    3.968218] usb 2-1.8.1.1: new full-speed USB device number 7 using ehci-pci
[    3.973417] apple 0003:05AC:0252.0002: input,hidraw1: USB HID v1.11 Keyboard [Apple Inc. Apple Internal Keyboard / Trackpad] on usb-0000:00:1d.0-1.8.3/input0
[    3.973577] apple 0003:05AC:0252.0003: hidraw2: USB HID v1.11 Device [Apple Inc. Apple Internal Keyboard / Trackpad] on usb-0000:00:1d.0-1.8.3/input1
[    4.049132] usb 2-1.8.1.1: New USB device found, idVendor=05ac, idProduct=820a, bcdDevice= 1.00
[    4.049170] usb 2-1.8.1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0




[    7.403920] usbcore: registered new interface driver uvcvideo
[    7.798365] input: bcm5974 as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.8/2-1.8.3/2-1.8.3:1.2/input/input15
[    7.799077] usbcore: registered new interface driver bcm5974
[    8.410568] alg: No test for fips(ansi_cprng) (fips_ansi_cprng)


$ lsinput
/dev/input/event0
   bustype : BUS_HOST
   vendor  : 0x0
   product : 0x5
   version : 0
   name    : "Lid Switch"
   phys    : "PNP0C0D/button/input0"
   bits ev : (null) (null)

/dev/input/event1
   bustype : BUS_HOST
   vendor  : 0x0
   product : 0x1
   version : 0
   name    : "Power Button"
   phys    : "PNP0C0C/button/input0"
   bits ev : (null) (null)

/dev/input/event2
   bustype : BUS_HOST
   vendor  : 0x0
   product : 0x3
   version : 0
   name    : "Sleep Button"
   phys    : "PNP0C0E/button/input0"
   bits ev : (null) (null)

/dev/input/event3
   bustype : BUS_HOST
   vendor  : 0x0
   product : 0x1
   version : 0
   name    : "Power Button"
   phys    : "LNXPWRBN/button/input0"
   bits ev : (null) (null)

/dev/input/event4
   bustype : BUS_HOST
   vendor  : 0x0
   product : 0x6
   version : 0
   name    : "Video Bus"
   phys    : "LNXVIDEO/video/input0"
   bits ev : (null) (null)

/dev/input/event5
   bustype : BUS_USB
   vendor  : 0x5ac
   product : 0x8242
   version : 273
   name    : "Apple Computer, Inc. IR Receiver"
   phys    : "usb-0000:00:1d.0-1.8.2/input0"
   uniq    : ""
   bits ev : (null) (null) (null)

/dev/input/event6
   bustype : BUS_USB
   vendor  : 0x5ac
   product : 0x252
   version : 273
   name    : "Apple Inc. Apple Internal Keyboa"
   phys    : "usb-0000:00:1d.0-1.8.3/input0"
   uniq    : ""
   bits ev : (null) (null) (null) (null) (null)

/dev/input/event7
   bustype : BUS_USB
   vendor  : 0x0
   product : 0x0
   version : 4
   name    : "ACPI Virtual Keyboard Device"
   bits ev : (null) (null)

/dev/input/event9
   bustype : (null)
   vendor  : 0x0
   product : 0x0
   version : 0
   name    : "HDA Intel PCH Headphone"
   phys    : "ALSA"
   bits ev : (null) (null)

/dev/input/event10
   bustype : (null)
   vendor  : 0x0
   product : 0x0
   version : 0
   name    : "HDA Intel PCH HDMI/DP,pcm=3"
   phys    : "ALSA"
   bits ev : (null) (null)

/dev/input/event11
   bustype : (null)
   vendor  : 0x0
   product : 0x0
   version : 0
   name    : "HDA Intel PCH HDMI/DP,pcm=7"
   phys    : "ALSA"
   bits ev : (null) (null)

/dev/input/event12
   bustype : (null)
   vendor  : 0x0
   product : 0x0
   version : 0
   name    : "HDA Intel PCH HDMI/DP,pcm=8"
   phys    : "ALSA"
   bits ev : (null) (null)

/dev/input/event13
   bustype : BUS_HOST
   vendor  : 0x0
   product : 0x0
   version : 0
   name    : "applesmc"
   bits ev : (null) (null)

/dev/input/event14
   bustype : BUS_USB
   vendor  : 0x5ac
   product : 0x8509
   version : 1302
   name    : "FaceTime HD Camera (Built-in): "
   phys    : "usb-0000:00:1a.0-1.1/button"
   bits ev : (null) (null)

/dev/input/event15
   bustype : BUS_USB
   vendor  : 0x5ac
   product : 0x252
   version : 1
   name    : "bcm5974"
   phys    : "usb-0000:00:1d.0-1.8.3/input0"
   bits ev : (null) (null) (null)

   
   
$ xinput list
⎡ Virtual core pointer                          id=2    [master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer                id=4    [slave  pointer  (2)]
⎜   ↳ bcm5974                                   id=13   [slave  pointer  (2)]
⎣ Virtual core keyboard                         id=3    [master keyboard (2)]
    ↳ Virtual core XTEST keyboard               id=5    [slave  keyboard (3)]
    ↳ Power Button                              id=6    [slave  keyboard (3)]
    ↳ Video Bus                                 id=7    [slave  keyboard (3)]
    ↳ Power Button                              id=8    [slave  keyboard (3)]
    ↳ Sleep Button                              id=9    [slave  keyboard (3)]
    ↳ FaceTime HD Camera (Built-in):            id=10   [slave  keyboard (3)]
    ↳ Apple Computer, Inc. IR Receiver          id=11   [slave  keyboard (3)]
    ↳ Apple Inc. Apple Internal Keyboard / Trackpad     id=12   [slave  keyboard (3)]
    ↳ ACPI Virtual Keyboard Device              id=14   [slave  keyboard (3)]
    
`

**Comment by mqudsi** [comment]
Please open a new issue.
