### ISSUE TITLE
can't add permanent configuration

### ISSUE THREAD

**Issue by juba0x00** [mqudsi/syngesture#8]
- Firstly I want to thank you, this is the only gestures software that worked on my laptop, I tried `libinput-gestures`, `touchegg`, `fusuma` with `libinput` drivers but none of these worked.

# How to add a fixed event 
- each time I restart my laptop I find that `syngestures` is not working, even though a process is running in the background.
- The problem is the `device=path`, this is my configuration file: 
```
[[device]]
device = "/dev/input/event25"
<SNIP>
```
- every time the laptop restarts the event number of the touchpad changes, so I changed it to `/dev/input/event*` but this error happens
![image](https://user-images.githubusercontent.com/73611543/215709816-408a1089-fec9-4433-ba67-61ef2e0fa279.png)

**Comment by mqudsi** [comment]
Hello,

I'm glad to hear that syngestures worked for you where the other tools didn't. There is no support for wildcards, regular expressions, or glob patterns in the device path at this time, though it's not something I'm against in principle.

What Linux distribution are you using? I feel like there has to be a stable path to the device available *somewhere*, even if it's not at `/dev/input/event25`.

You might want to look at the entire output of `dmesg` after system startup to see where the device is being registered - but it still might not show there depending on who creates the stable symlink (assuming there is one). 

What other devices do you have under `/dev/input/`? Is there any way of systemically/programmatically determining which is the touchpad?

**Comment by juba0x00** [comment]
- `/dev/input/by-path/platform-i8042-serio-1-event-mouse` This path is a link to the event file.

**Comment by juba0x00** [comment]
thank you
after searching, I found this path like your documentation `/dev/input/by-path/platform-i8042-serio-1-event-mouse`.
I'm sorry for bothering you.
